package outcome;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("First Name")
   private java.lang.String PRI_FIRSTNAME;
   @org.kie.api.definition.type.Label("Load Code")
   private java.lang.String PRI_CODE;
   @org.kie.api.definition.type.Label("Username")
   private java.lang.String PRI_USERNAME;
   @org.kie.api.definition.type.Label("Keycloak ID")
   private java.lang.Integer PRI_KEYCLOAK_ID;
   @org.kie.api.definition.type.Label("Last Name")
   private java.lang.String PRI_LASTNAME;
   @org.kie.api.definition.type.Label("Date of birth")
   private java.util.Date PRI_DOB;
   @org.kie.api.definition.type.Label("Street address with number")
   private java.lang.String PRI_ADDRESS_STREET;
   @org.kie.api.definition.type.Label("Suburb")
   private java.lang.String PRI_ADDRESS_SUBURB;
   @org.kie.api.definition.type.Label("Postcode")
   private java.lang.Integer PRI_ADDRESS_POSTCODE;
   @org.kie.api.definition.type.Label("State")
   private java.lang.String PRI_ADDRESS_STATE;
   @org.kie.api.definition.type.Label("Country")
   private java.lang.String PRI_ADDRESS_COUNTRY;
   @org.kie.api.definition.type.Label("Mobile Number")
   private java.lang.Long PRI_MOBILENUMBER;
   @org.kie.api.definition.type.Label("Account Type")
   private String PRI_ROLE;

   @org.kie.api.definition.type.Label("Email")
   private java.lang.String PRI_EMAIL;

   @org.kie.api.definition.type.Label("Password")
   private java.lang.String PRI_PASSWORD;

   public User()
   {
   }

   public java.lang.String getPRI_FIRSTNAME()
   {
      return this.PRI_FIRSTNAME;
   }

   public void setPRI_FIRSTNAME(java.lang.String PRI_FIRSTNAME)
   {
      this.PRI_FIRSTNAME = PRI_FIRSTNAME;
   }

   public java.lang.String getPRI_CODE()
   {
      return this.PRI_CODE;
   }

   public void setPRI_CODE(java.lang.String PRI_CODE)
   {
      this.PRI_CODE = PRI_CODE;
   }

   public java.lang.String getPRI_USERNAME()
   {
      return this.PRI_USERNAME;
   }

   public void setPRI_USERNAME(java.lang.String PRI_USERNAME)
   {
      this.PRI_USERNAME = PRI_USERNAME;
   }

   public java.lang.Integer getPRI_KEYCLOAK_ID()
   {
      return this.PRI_KEYCLOAK_ID;
   }

   public void setPRI_KEYCLOAK_ID(java.lang.Integer PRI_KEYCLOAK_ID)
   {
      this.PRI_KEYCLOAK_ID = PRI_KEYCLOAK_ID;
   }

   public java.lang.String getPRI_LASTNAME()
   {
      return this.PRI_LASTNAME;
   }

   public void setPRI_LASTNAME(java.lang.String PRI_LASTNAME)
   {
      this.PRI_LASTNAME = PRI_LASTNAME;
   }

   public java.util.Date getPRI_DOB()
   {
      return this.PRI_DOB;
   }

   public void setPRI_DOB(java.util.Date PRI_DOB)
   {
      this.PRI_DOB = PRI_DOB;
   }

   public java.lang.String getPRI_ADDRESS_STREET()
   {
      return this.PRI_ADDRESS_STREET;
   }

   public void setPRI_ADDRESS_STREET(java.lang.String PRI_ADDRESS_STREET)
   {
      this.PRI_ADDRESS_STREET = PRI_ADDRESS_STREET;
   }

   public java.lang.String getPRI_ADDRESS_SUBURB()
   {
      return this.PRI_ADDRESS_SUBURB;
   }

   public void setPRI_ADDRESS_SUBURB(java.lang.String PRI_ADDRESS_SUBURB)
   {
      this.PRI_ADDRESS_SUBURB = PRI_ADDRESS_SUBURB;
   }

   public java.lang.Integer getPRI_ADDRESS_POSTCODE()
   {
      return this.PRI_ADDRESS_POSTCODE;
   }

   public void setPRI_ADDRESS_POSTCODE(java.lang.Integer PRI_ADDRESS_POSTCODE)
   {
      this.PRI_ADDRESS_POSTCODE = PRI_ADDRESS_POSTCODE;
   }

   public java.lang.String getPRI_ADDRESS_STATE()
   {
      return this.PRI_ADDRESS_STATE;
   }

   public void setPRI_ADDRESS_STATE(java.lang.String PRI_ADDRESS_STATE)
   {
      this.PRI_ADDRESS_STATE = PRI_ADDRESS_STATE;
   }

   public java.lang.String getPRI_ADDRESS_COUNTRY()
   {
      return this.PRI_ADDRESS_COUNTRY;
   }

   public void setPRI_ADDRESS_COUNTRY(java.lang.String PRI_ADDRESS_COUNTRY)
   {
      this.PRI_ADDRESS_COUNTRY = PRI_ADDRESS_COUNTRY;
   }

   public java.lang.Long getPRI_MOBILENUMBER()
   {
      return this.PRI_MOBILENUMBER;
   }

   public void setPRI_MOBILENUMBER(java.lang.Long PRI_MOBILENUMBER)
   {
      this.PRI_MOBILENUMBER = PRI_MOBILENUMBER;
   }

   public java.lang.String getPRI_EMAIL()
   {
      return this.PRI_EMAIL;
   }

   public void setPRI_EMAIL(java.lang.String PRI_EMAIL)
   {
      this.PRI_EMAIL = PRI_EMAIL;
   }

   public java.lang.String getPRI_PASSWORD()
   {
      return this.PRI_PASSWORD;
   }

   public void setPRI_PASSWORD(java.lang.String PRI_PASSWORD)
   {
      this.PRI_PASSWORD = PRI_PASSWORD;
   }

   public java.lang.String getPRI_ROLE()
   {
      return this.PRI_ROLE;
   }

   public void setPRI_ROLE(java.lang.String PRI_ROLE)
   {
      this.PRI_ROLE = PRI_ROLE;
   }

   public User(java.lang.String PRI_FIRSTNAME, java.lang.String PRI_CODE,
         java.lang.String PRI_USERNAME, java.lang.Integer PRI_KEYCLOAK_ID,
         java.lang.String PRI_LASTNAME, java.util.Date PRI_DOB,
         java.lang.String PRI_ADDRESS_STREET,
         java.lang.String PRI_ADDRESS_SUBURB,
         java.lang.Integer PRI_ADDRESS_POSTCODE,
         java.lang.String PRI_ADDRESS_STATE,
         java.lang.String PRI_ADDRESS_COUNTRY, java.lang.Long PRI_MOBILENUMBER,
         java.lang.String PRI_ROLE, java.lang.String PRI_EMAIL,
         java.lang.String PRI_PASSWORD)
   {
      this.PRI_FIRSTNAME = PRI_FIRSTNAME;
      this.PRI_CODE = PRI_CODE;
      this.PRI_USERNAME = PRI_USERNAME;
      this.PRI_KEYCLOAK_ID = PRI_KEYCLOAK_ID;
      this.PRI_LASTNAME = PRI_LASTNAME;
      this.PRI_DOB = PRI_DOB;
      this.PRI_ADDRESS_STREET = PRI_ADDRESS_STREET;
      this.PRI_ADDRESS_SUBURB = PRI_ADDRESS_SUBURB;
      this.PRI_ADDRESS_POSTCODE = PRI_ADDRESS_POSTCODE;
      this.PRI_ADDRESS_STATE = PRI_ADDRESS_STATE;
      this.PRI_ADDRESS_COUNTRY = PRI_ADDRESS_COUNTRY;
      this.PRI_MOBILENUMBER = PRI_MOBILENUMBER;
      this.PRI_ROLE = PRI_ROLE;
      this.PRI_EMAIL = PRI_EMAIL;
      this.PRI_PASSWORD = PRI_PASSWORD;
   }

}